enabled : true # Enable or disable the plugin

combat-tag-duration: 30 # Duration in seconds for how long a player is in combat after being hit or hitting another player

punishment-method: kill # Punishment for combat logging: 'kill' or 'ban'
ban-duration: 1440 # Duration in minutes for temporary bans (only if punishment-method is 'ban') (1440 minutes = 24 hours) (set to -1 for permanent ban)

enable-in-creative: false # Whether to enable combat logging in creative mode

retaliationattack: false # Enable combat tag only on retaliation attacks
retaliationattack-duration: 10 # Duration in seconds for retaliation attack window (only if retaliationattack is true)
set-attacker-on-combat: true # Whether to set the attacker as in combat when they hit another player (only if retaliationattack is true)

allow-portal-teleport: false # Whether to allow teleporting via portals while in combat

blocked-commands: #List of commands that are disabled during combat (without slash)
  - "home"
  - "spawn"
  - "warp"
  - "tpa"

disabled-worlds: # List of worlds where combat logging is disabled
  - "world_the_end"